var N = null;var sourcesIndex = {};
sourcesIndex["pallet_amm"] = {"name":"","files":["lib.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_asset_registry"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_bridge"] = {"name":"","files":["lib.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_crowdloans"] = {"name":"","files":["lib.rs","migrations.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_currency_adapter"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_emergency_shutdown"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_farming"] = {"name":"","files":["lib.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_liquid_staking"] = {"name":"","files":["distribution.rs","lib.rs","migrations.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_loans"] = {"name":"","files":["farming.rs","interest.rs","lib.rs","migrations.rs","ptoken.rs","rate_model.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_loans_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_loans_rpc_runtime_api"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_prices"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_router"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_router_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_router_rpc_runtime_api"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_streaming"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_traits"] = {"name":"","files":["lib.rs","ump.rs","xcm.rs"]};
sourcesIndex["pallet_xcm_helper"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["parallel_primitives"] = {"name":"","files":["lib.rs","network.rs","tokens.rs"]};
createSourceSidebar();
