[package]
authors = ['Parallel Team']
edition = '2021'
name    = 'pallet-payroll'
version = '1.7.8'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec              = { package = 'parity-scale-codec', version = '2.3.1', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false, optional = true }
frame-support      = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
frame-system       = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
orml-traits        = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
pallet-assets      = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
pallet-balances    = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
pallet-prices      = { path = '../prices', default-features = false }
pallet-timestamp   = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
scale-info         = { version = '1.0', default-features = false, features = ['derive'] }

primitives = { package = 'parallel-primitives', path = '../../primitives', default-features = false }
serde      = { version = '1', features = ['derive'], optional = true }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
sp-std     = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }

[dev-dependencies]
orml-oracle             = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git' }
pallet-currency-adapter = { path = '../currency-adapter' }
sp-core                 = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }
sp-io                   = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.17', default-features = false }


[features]
default            = ['std']
runtime-benchmarks = ['frame-benchmarking']
std                = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'orml-traits/std',
  'primitives/std',
  'sp-runtime/std',
  'sp-std/std',
  'pallet-balances/std',
  'pallet-timestamp/std',
  'serde',
  'scale-info/std',
]
try-runtime = ['frame-support/try-runtime']

[lib]
doctest = false
