[package]
authors     = ['Parallel Team']
build       = 'build.rs'
description = 'A decentralized lending protocol which allow users to earn "double interests" from staking and lending'
edition     = '2021'
homepage    = 'https://parallel.fi'
license     = 'Apache'
name        = 'kerria-runtime'
repository  = 'https://github.com/parallel-finance/parallel'
version     = '1.8.6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec             = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = ['derive'] }
hex-literal       = '0.3.3'
serde             = { version = '1.0.136', features = ['derive'], optional = true }
smallvec          = '1.6.1'
static_assertions = '1.1.0'

# Substrate dependencies
frame-benchmarking                         = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false, optional = true }
frame-executive                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
frame-support                              = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
frame-system                               = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
frame-system-benchmarking                  = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false, optional = true }
frame-system-rpc-runtime-api               = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
frame-try-runtime                          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false, optional = true }
pallet-assets                              = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-aura                                = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-authorship                          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-balances                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-collective                          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-democracy                           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-identity                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-membership                          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-multisig                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-preimage                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-proxy                               = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-scheduler                           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-session                             = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-sudo                                = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-timestamp                           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-transaction-payment                 = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-treasury                            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-utility                             = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
scale-info                                 = { version = '2.1', default-features = false, features = ['derive'] }
sp-api                                     = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-block-builder                           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-consensus-aura                          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-core                                    = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-inherents                               = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-offchain                                = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-runtime                                 = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-session                                 = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-std                                     = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-transaction-pool                        = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }
sp-version                                 = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }

# Polkadot dependencies
pallet-xcm              = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }
polkadot-parachain      = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }
polkadot-runtime-common = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }
xcm                     = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }
xcm-builder             = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }
xcm-executor            = { git = 'https://github.com/paritytech/polkadot.git', branch = 'release-v0.9.19', default-features = false }

# Cumulus dependencies
cumulus-pallet-aura-ext         = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-pallet-dmp-queue        = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-pallet-parachain-system = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-pallet-xcm              = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-pallet-xcmp-queue       = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-primitives-core         = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-primitives-timestamp    = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
cumulus-primitives-utility      = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
pallet-collator-selection       = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }
parachain-info                  = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.19', default-features = false }

# ORML dependencies
orml-oracle                 = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-oracle-rpc-runtime-api = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-traits                 = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-vesting                = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-xcm                    = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-xcm-support            = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }
orml-xtokens                = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', branch = 'polkadot-v0.9.19', default-features = false }

# Parallel dependencies
pallet-amm                    = { path = '../../pallets/amm', default-features = false }
pallet-asset-registry         = { path = '../../pallets/asset-registry', default-features = false }
pallet-bridge                 = { path = '../../pallets/bridge', default-features = false }
pallet-crowdloans             = { path = '../../pallets/crowdloans', default-features = false }
pallet-currency-adapter       = { path = '../../pallets/currency-adapter', default-features = false }
pallet-emergency-shutdown     = { path = '../../pallets/emergency-shutdown', default-features = false }
pallet-farming                = { path = '../../pallets/farming', default-features = false }
pallet-liquid-staking         = { path = '../../pallets/liquid-staking', default-features = false }
pallet-loans                  = { path = '../../pallets/loans', default-features = false }
pallet-loans-rpc-runtime-api  = { path = '../../pallets/loans/rpc/runtime-api', default-features = false }
pallet-prices                 = { path = '../../pallets/prices', default-features = false }
pallet-router                 = { path = '../../pallets/router', default-features = false }
pallet-router-rpc-runtime-api = { path = '../../pallets/router/rpc/runtime-api', default-features = false }
pallet-streaming              = { path = '../../pallets/streaming', default-features = false }
pallet-traits                 = { path = '../../pallets/traits', default-features = false }
pallet-xcm-helper             = { path = '../../pallets/xcm-helper', default-features = false }
primitives                    = { package = 'parallel-primitives', path = '../../primitives', default-features = false }

[build-dependencies.substrate-wasm-builder]
branch = 'polkadot-v0.9.19'
git    = 'https://github.com/paritytech/substrate.git'

[dev-dependencies]
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.19', default-features = false }

[features]
default            = ['std']
runtime-benchmarks = [
  'sp-runtime/runtime-benchmarks',
  'frame-benchmarking',
  'frame-support/runtime-benchmarks',
  'frame-system-benchmarking',
  'frame-system/runtime-benchmarks',
  'pallet-balances/runtime-benchmarks',
  'pallet-bridge/runtime-benchmarks',
  'pallet-timestamp/runtime-benchmarks',
  'pallet-loans/runtime-benchmarks',
  'pallet-liquid-staking/runtime-benchmarks',
  'pallet-collective/runtime-benchmarks',
  'pallet-xcm/runtime-benchmarks',
  'xcm-builder/runtime-benchmarks',
  'pallet-multisig/runtime-benchmarks',
  'pallet-membership/runtime-benchmarks',
  'pallet-amm/runtime-benchmarks',
  'pallet-router/runtime-benchmarks',
  'pallet-crowdloans/runtime-benchmarks',
  'pallet-xcm-helper/runtime-benchmarks',
  'pallet-farming/runtime-benchmarks',
  'pallet-asset-registry/runtime-benchmarks',
  'pallet-streaming/runtime-benchmarks',
]
std                = [
  'codec/std',
  'serde',
  'scale-info/std',
  'sp-api/std',
  'sp-std/std',
  'sp-core/std',
  'sp-runtime/std',
  'sp-version/std',
  'sp-offchain/std',
  'sp-session/std',
  'sp-block-builder/std',
  'sp-transaction-pool/std',
  'sp-inherents/std',
  'sp-consensus-aura/std',
  'frame-support/std',
  'frame-executive/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'frame-system-rpc-runtime-api/std',
  'pallet-balances/std',
  'pallet-xcm/std',
  'pallet-timestamp/std',
  'pallet-sudo/std',
  'pallet-transaction-payment/std',
  'pallet-transaction-payment-rpc-runtime-api/std',
  'parachain-info/std',
  'polkadot-parachain/std',
  'cumulus-pallet-parachain-system/std',
  'cumulus-primitives-core/std',
  'cumulus-primitives-utility/std',
  'cumulus-pallet-xcmp-queue/std',
  'cumulus-pallet-dmp-queue/std',
  'cumulus-pallet-aura-ext/std',
  'cumulus-pallet-xcm/std',
  'xcm/std',
  'xcm-builder/std',
  'xcm-executor/std',
  'primitives/std',
  'pallet-bridge/std',
  'pallet-loans/std',
  'pallet-loans-rpc-runtime-api/std',
  'pallet-router-rpc-runtime-api/std',
  'pallet-liquid-staking/std',
  'pallet-streaming/std',
  'pallet-prices/std',
  'pallet-multisig/std',
  'pallet-utility/std',
  'pallet-proxy/std',
  'pallet-aura/std',
  'orml-oracle/std',
  'orml-oracle-rpc-runtime-api/std',
  'orml-traits/std',
  'pallet-treasury/std',
  'pallet-collective/std',
  'pallet-membership/std',
  'pallet-democracy/std',
  'pallet-identity/std',
  'pallet-scheduler/std',
  'pallet-preimage/std',
  'polkadot-runtime-common/std',
  'pallet-session/std',
  'pallet-authorship/std',
  'pallet-collator-selection/std',
  'cumulus-primitives-timestamp/std',
  'orml-xcm-support/std',
  'orml-xtokens/std',
  'orml-xcm/std',
  'orml-vesting/std',
  'pallet-amm/std',
  'pallet-router/std',
  'frame-try-runtime/std',
  'pallet-currency-adapter/std',
  'pallet-crowdloans/std',
  'pallet-emergency-shutdown/std',
  'pallet-xcm-helper/std',
  'pallet-farming/std',
  'pallet-asset-registry/std',
  'pallet-traits/std',
]
try-runtime        = [
  'frame-support/try-runtime',
  'frame-executive/try-runtime',
  'frame-system/try-runtime',
  'pallet-balances/try-runtime',
  'pallet-timestamp/try-runtime',
  'pallet-sudo/try-runtime',
  'pallet-transaction-payment/try-runtime',
  'pallet-multisig/try-runtime',
  'pallet-utility/try-runtime',
  'pallet-aura/try-runtime',
  'orml-oracle/try-runtime',
  'pallet-treasury/try-runtime',
  'pallet-collective/try-runtime',
  'pallet-membership/try-runtime',
  'pallet-democracy/try-runtime',
  'pallet-identity/try-runtime',
  'pallet-scheduler/try-runtime',
  'pallet-preimage/try-runtime',
  'polkadot-runtime-common/try-runtime',
  'pallet-session/try-runtime',
  'pallet-assets/try-runtime',
  'pallet-authorship/try-runtime',
  'orml-xtokens/try-runtime',
  'orml-xcm/try-runtime',
  'orml-vesting/try-runtime',
  'frame-try-runtime',
  'pallet-bridge/try-runtime',
  'pallet-loans/try-runtime',
  'pallet-liquid-staking/try-runtime',
  'pallet-streaming/try-runtime',
  'pallet-prices/try-runtime',
  'pallet-crowdloans/try-runtime',
  'pallet-xcm-helper/try-runtime',
  'pallet-asset-registry/try-runtime',
]
