[package]
name = "precompile-utils"
authors = { workspace = true }
edition = '2021'
version = { workspace = true }

[dependencies]
impl-trait-for-tuples = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true }
similar-asserts = { workspace = true, optional = true }

precompile-utils-macro = { path = "macro" }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
evm = { workspace = true, features = ["with-codec"] }
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ['forbid-evm-reentrancy'] }

# Polkadot / XCM
xcm = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
sha3 = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"sp-runtime/std",
	"xcm/std",
]
testing = ["similar-asserts", "std"]
