[package]
authors = { workspace = true }
edition = '2021'
name    = 'pallet-xcm-helper'
version = { workspace = true }

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec              = { package = 'parity-scale-codec', version = '3.1.5', features = ['max-encoded-len'], default-features = false }
frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }
pallet-assets      = { workspace = true }
pallet-traits      = { workspace = true }
pallet-xcm         = { workspace = true }
primitives         = { workspace = true }
scale-info         = { workspace = true, features = ['derive'] }
sp-core            = { workspace = true }
sp-io              = { workspace = true }
sp-runtime         = { workspace = true }
sp-std             = { workspace = true }
xcm                = { workspace = true }
xcm-executor       = { workspace = true }

[dev-dependencies]
cumulus-pallet-dmp-queue        = { workspace = true, features = ['std'] }
cumulus-pallet-parachain-system = { workspace = true, features = ['std'] }
cumulus-pallet-xcm              = { workspace = true, features = ['std'] }
cumulus-pallet-xcmp-queue       = { workspace = true, features = ['std'] }
kusama-runtime                  = { workspace = true, features = ['runtime-benchmarks'] }
orml-xcm-support                = { workspace = true, features = ['std'] }
pallet-babe                     = { workspace = true, features = ['std'] }
pallet-balances                 = { workspace = true, features = ['std'] }
pallet-session                  = { workspace = true, features = ['std'] }
pallet-timestamp                = { workspace = true, features = ['std'] }
pallet-utility                  = { workspace = true, features = ['std'] }
parachain-info                  = { workspace = true, features = ['std'] }
polkadot-core-primitives        = { workspace = true }
polkadot-parachain              = { workspace = true, features = ['std'] }
polkadot-runtime-parachains     = { workspace = true }
serde                           = { workspace = true }
sp-io                           = { workspace = true }
xcm-builder                     = { workspace = true, features = ['std'] }
xcm-executor                    = { workspace = true, features = ['std'] }
xcm-simulator                   = { workspace = true }

[features]
default            = ['std']
runtime-benchmarks = ['frame-benchmarking']
std                = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'sp-runtime/std',
  'scale-info/std',
  'sp-std/std',
  'xcm/std',
  'xcm-executor/std',
  'pallet-assets/std',
  'pallet-xcm/std',
  'primitives/std',
  'pallet-traits/std',
]
try-runtime        = ['frame-support/try-runtime']

[lib]
doctest = false
