[package]
authors = { workspace = true }
edition = '2021'
name    = 'pallet-traits'
version = { workspace = true }

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde         = { workspace = true, features = ['derive'], optional = true }
codec         = { workspace = true, features = ['max-encoded-len'] }
frame-support = { workspace = true }
frame-system  = { workspace = true }
log           = { workspace = true }
num-bigint    = { workspace = true }
num-traits    = { workspace = true }
primitives    = { workspace = true }
scale-info    = { workspace = true, features = ['derive'] }
sp-core       = { workspace = true }
sp-io         = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }
xcm           = { workspace = true }
xcm-builder   = { workspace = true }
xcm-executor  = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true, features = ['std'] }

[features]
default = ['std']
std     = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-runtime/std',
  'scale-info/std',
  'sp-std/std',
  'primitives/std',
  'num-bigint/std',
  'num-traits/std',
  'sp-core/std',
  'xcm-executor/std',
  'xcm/std',
  'xcm-builder/std',
]

try-runtime = ['frame-support/try-runtime']

[lib]
doctest = false
