name: Benchmarking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'parallel-finance/parallel'
    name: Auto Build CI
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
        
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
          default: true
          components: rustfmt, clippy

#       - name: Build Benchmarking Release And Package
#         run: |
#           cargo build --bin parallel-dev --release --features runtime-benchmarks
#           rm -fr dist || true
#           mkdir dist || true
#           cp .maintain/frame-weight-template.hbs dist
#           cp target/release/parallel-dev dist/parallel
#           tar -cvJf parallel.tar.xz dist --transform 's|dist|parallel|'
          
#       - name: Copy File Via Ssh Password
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.WEIGHTS_SSH_HOST }}
#           username: ${{ secrets.WEIGHTS_SSH_USERNAME }}
#           key: ${{ secrets.WEIGHTS_SSH_PRIVKEY }}
#           port: ${{ secrets.WEIGHTS_SSH_PORT }}
#           source: "*.tar.xz"
#           target: "~"
          
#       - name: Calculate Weights
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.WEIGHTS_SSH_HOST }}
#           username: ${{ secrets.WEIGHTS_SSH_USERNAME }}
#           key: ${{ secrets.WEIGHTS_SSH_PRIVKEY }}
#           port: ${{ secrets.WEIGHTS_SSH_PORT }}
#           script: |
#             rm -fr parallel
#             tar -Jxf parallel.tar.xz
#             ls
#             cd parallel && ./parallel benchmark --chain=dev --execution=wasm --wasm-execution=compiled --pallet=pallet_loans --extrinsic='*' --steps=50 --repeat=20 --heap-pages=4096 --template=./frame-weight-template.hbs --output=weights.rs
      
      - name: Download weight via SSH
        run: |
          ssh-keygen -t rsa
          ssh-copy-id ${{ secrets.WEIGHTS_SSH_USERNAME }}@${{ secrets.WEIGHTS_SSH_HOST }}
          scp -i ~/.ssh/id_rsa.pub ${{ secrets.WEIGHTS_SSH_USERNAME }}@${{ secrets.WEIGHTS_SSH_HOST }}:parallel/weights.rs ./pallets/loans/src/weights.rs
#         uses: nicklasfrahm/scp-action@main
#         with:
#           direction: download
#           host: ${{ secrets.WEIGHTS_SSH_HOST }}
#           username: ${{ secrets.WEIGHTS_SSH_USERNAME }}
#           key: ${{ secrets.WEIGHTS_SSH_PRIVKEY }}
#           port: ${{ secrets.WEIGHTS_SSH_PORT }}
#           source: parallel/weights.rs
#           target: ./pallets/loans/src/weights.rs        
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          message: 'Updated weights'
          add: '*.rs'
