name: njsscan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: "."
