name: Njsscan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: "."
