name: Update types.json

on:
  workflow_dispatch:

jobs:
  updateFrontendTypes:
    if: github.repository == 'parallel-finance/parallel'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [testnet]
        repo: [parallel-dapp]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: parallel-finance/${{matrix.repo}}
          ref: ${{matrix.branch}}
          token: ${{secrets.PAT}}
      - name: Pull latest types.json
        run: |
          curl -fLo src/config/types.json https://raw.githubusercontent.com/parallel-finance/parallel/master/resources/types.json
      - name: Check for modified files
        id: modified_check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Push latest changes
        if: steps.modified_check.outputs.modified == 'true'
        run: |
          set -x
          git config --global user.name "Github Actions"
          git config --global user.email "Github Actions"
          if [ -z "$(git status --porcelain)" ]
          then
              echo "nothing to update."
          else
              git add src/config/types.json
              git commit -m "update types.json"
          fi
          git push "https://${{ secrets.PAT }}@github.com/parallel-finance/${{matrix.repo}}.git" HEAD:${{matrix.branch}}

  updateFaucetTypes:
    if: github.repository == 'parallel-finance/parallel'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master]
        repo: [faucet-bot]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: parallel-finance/${{matrix.repo}}
          ref: ${{matrix.branch}}
          token: ${{secrets.PAT}}
      - name: Pull latest types.json
        run: |
          curl -fLo src/config/types.json https://raw.githubusercontent.com/parallel-finance/parallel/master/resources/types.json
      - name: Check for modified files
        id: modified_check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Push latest changes
        if: steps.modified_check.outputs.modified == 'true'
        run: |
          set -x
          git config --global user.name "Github Actions"
          git config --global user.email "Github Actions"
          if [ -z "$(git status --porcelain)" ]
          then
              echo "nothing to update."
          else
              git add src/config/types.json
              git commit -m "update types.json"
          fi
          git push "https://${{ secrets.PAT }}@github.com/parallel-finance/${{matrix.repo}}.git" HEAD:${{matrix.branch}}
